### ISSUE TITLE
query option

### ISSUE THREAD

**Issue by sunchang1990** [sami-chaaban/starparser#1]
This is a very useful package for cryoEM practitioners. One issue I encoutered is the query option, in which a slash is used as the "or" operator. In that case, can one use the back slash to escape the function of a slash and query a string with slash in it? Additionally, how is the query match being executed?

**Comment by sami-chaaban** [comment]
I've added an escape option to the latest version. Use a comma preceding the slash to escape it (i.e. foo,/bar). Update your starparser with `pip install --upgrade starparser`. 

The following line is executed for each query: `extractedparticles.drop(extractedparticles[~extractedparticles[columns[0]].str.contains(q)].index, 0,inplace=True)`.
The "~" refers to "not", so particles that don't contain the query will be dropped from the pandas dataframe.
