### ISSUE TITLE
fileparser API calling sys.exit() rather than throwing an exception

### ISSUE THREAD

**Issue by enricotagliavini** [sami-chaaban/starparser#2]
Hello,

I'm using starparser to read information out of relion starfiles. Today I opened a relion 3.0 format star file by accident. This file format is probably old and not supported by starparser, which is fine, but the part that throws me off is that the fileparser API, namely the getparticles() function, will simply call sys.exit() when encountering an exception, including any parsing problem.

See line https://github.com/sami-chaaban/starparser/blob/822cd9413ebfa56ce7dbbebbfb08693f08060895/starparser/fileparser.py#L36

This is not a good behavior for an API, it better to throw a meaningful exception and let the API consumer to decide what do to and clean up before interrupting the execution.

The same API also has print statements, which should probably be turned off by default and enabled only via a debug or verbose flag. Example:

https://github.com/sami-chaaban/starparser/blob/822cd9413ebfa56ce7dbbebbfb08693f08060895/starparser/fileparser.py#L11

**Comment by sami-chaaban** [comment]
Removed the empty exception.
